FROM python:3-slim

WORKDIR /app

RUN apt-get update
RUN apt-get install -y wget ffmpeg

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

RUN adduser vladfedchenko --quiet
# CMD ["bash"]
